/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.courriermanagementsystem;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author surajpandey
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_title = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jButton_manager = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_delivery = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COURRIER MANAGEMENT SYSTEM");
        setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_title.setBackground(new java.awt.Color(51, 51, 0));
        jPanel_title.setToolTipText("");

        jLabel_title.setFont(new java.awt.Font("Zapfino", 0, 24)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText("COURRIER MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jLabel_title)
                .addGap(239, 239, 239))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel_title)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        jButton_manager.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_manager.setText("managing staff");
        jButton_manager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_managerActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 220, 60));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Customer");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 230, 60));

        jButton_exit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_exit.setText("Exit");
        jButton_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 130, 40));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("!!--WELCOME--!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jButton_delivery.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_delivery.setText("delivery staff");
        jButton_delivery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deliveryActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 220, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/surajpandey/Desktop/forback.jpeg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_managerActionPerformed
       
         ManagerLogin ml = new  ManagerLogin();
        ml.setVisible(true);
        
    }//GEN-LAST:event_jButton_managerActionPerformed

    private void jButton_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deliveryActionPerformed
        DeliveryPersonLogin dsp = new DeliveryPersonLogin();
        dsp.setVisible(true);
    }//GEN-LAST:event_jButton_deliveryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       CurrentLocation cl = new CurrentLocation();
       cl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int i = JOptionPane.showConfirmDialog(f,"DO YOU WANT TO EXIT?");
        if(i==JOptionPane.YES_OPTION)
        {
           // f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jButton_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_delivery;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_manager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel_title;
    // End of variables declaration//GEN-END:variables
}
